name: 自动push防止Actions自动停止

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,15 * *'
  repository_dispatch:
    types: [start_action]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 只留这一个，官方推荐提前启用 Node24 ✅
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id || github.actor == 'BlueSkyClouds'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 配置 Git
        run: |
          git config --global user.name "Biang0"
          git config --global user.email "wangyuan0999@gmail.com"

      - name: 创建空提交
        run: git commit --allow-empty -m "Auto keep active"

      - name: 推送到 script 分支
        run: git push origin HEAD:script
